### ISSUE TITLE
Domain list does not load

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/cpanel-addon#20] opened 2017-08-23 06:11 UTC
### Version information
```
Addon version: 3.0.96517
Diagnostics Results :

PHP version: OK!
PHP extensions: OK!
Configuration binary: OK!
Configuration permissions: OK!
Panel version: OK!
Addon version: OK!
Hashes: OK!
Hooks: OK!
Symlinks: OK!
Controlpanel API: OK!
Spamfilter API: OK!

cPanel version : v66.0.14
```

### Steps to replicate

 1. Client received the update
 2. He tried to check his domain list
 3. Page displayed "Loading your domainnames
`Please contact support if this page doesn't load!`

### Actual result
Domain list does not load

### Expected result
Domain list should load

### Other notes
[WHMCS](https://my.spamexperts.com/admin/supporttickets.php?action=view&id=179201)

**Comment by alexkiro** [comment] 2017-08-23 06:24
Duplicate of #18

**Closed by alexkiro** 2017-08-23 06:24 UTC
Labels: bug, duplicate, priority-normal
